### ISSUE TITLE
Upload launcher .ini files from yarp-devices

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/asibot-configuration-files#1]
We host copies of [oneCanBusOneWrapper.ini](https://github.com/roboticslab-uc3m/yarp-devices/blob/1632d72a7f6a2bf601dac52628226e4a1f319472/share/oneCanBusOneWrapper/conf/oneCanBusOneWrapper.ini) at `/home/asibot2/.local/yarp/`, conveniently adapted for use in ASIBOT's demos and experiments (with or without CUIs and Lacquey). Most importantly, transmission values and motion limits are hosted there and nowhere else. We really should store such info here and clone this repo aboard.

**Comment by PeterBowman** [comment]
Current template:

```
[devCan0]
device CanBusControlboard
canDevice /dev/can0
canBusType CanBusHico
types TechnosoftIpos TechnosoftIpos TechnosoftIpos TechnosoftIpos TechnosoftIpos LacqueyFetch
ids   1 2 3 4 5 65
maxs  360 135 135 135 360 1200
mins -360 -135 -135 -135 -360 -1200
trs   160 160 160 160 160 0
maxVels 15 15 15 15 15 0
refAccelerations  10 10 10 10 10 0
refSpeeds  10 10 10 10 10 0
encoderPulsess 4096 4096 4096 4096 4096 0

[wrapper0]
device controlboardwrapper2
name /canbot/arm
period 60
joints 6
networks (devCan0)
devCan0 0 5 0 5
```

Need to decide on:
* with/without LacqueyFetch
* CAN device and node (HiCO.CAN vs Peak-CAN)
* port name for wrapper device.
  * /asibot is currently taken by yarprun
  * composite name (/a/b instead of just /a) so that yarpmotorgui can interface with it

**Comment by jgvictores** [comment]
`/asibot/arm` doesn't look like a bad idea, to distinguish if from the hand...

**Comment by PeterBowman** [comment]
I wonder if yarpmotorgui would choke on /asibot (it has to query all robot parts somehow).

**Comment by jgvictores** [comment]
Yes, possibly that would happen too.

**Comment by PeterBowman** [comment]
WIP because of https://github.com/roboticslab-uc3m/yarp-devices/issues/237 and https://github.com/roboticslab-uc3m/yarp-devices/pull/229.

**Comment by PeterBowman** [comment]
I can't find any references on the Kollmorgen QT1917 motor. The oldest datasheets I could locate are these ones (2005): [Direct_Drive_DC_Torque_Motors_Catalog_2005.pdf](https://github.com/roboticslab-uc3m/asibot-configuration-files/files/4005241/Direct_Drive_DC_Torque_Motors_Catalog_2005.pdf), [NT_QT_T_Catalog.pdf (gdrive)](https://drive.google.com/open?id=1S8tv5BTC4LqOA-wpF38AGSp2UkOHAmjW). Therefore, I cannot establish the actual value of the [motor torque constant](https://en.wikipedia.org/wiki/Motor_constants#Motor_torque_constant).

**Comment by jgvictores** [comment]
While I was skeptical there could be a typo or similar, note that there are actual pictures where components are stamped "qt-1917-a".

**Comment by jgvictores** [comment]
Older document, still no "qt-1917-a":
- https://www.kollmorgen.com/sites/default/files/public_downloads/Kollmorgen%20Inland%20Motor%20Direct%20Drive%20DC%20Motors%20Catalog%20EN.pdf = https://www.kollmorgen.com/sites/default/files/NT_QT_T_Catalog.pdf

Note that Kollmorgen offers custom variations. Maybe @smcdiaz knows better. ^^

**Comment by PeterBowman** [comment]
New *manipulator.ini*:

https://github.com/roboticslab-uc3m/asibot-configuration-files/blob/e02bfc67c363cf0353ad78921904ed50f59b1ac5/share/contexts/launchCanBus/manipulator.ini#L1-L14

See also *manipulator-lacquey.ini*:

https://github.com/roboticslab-uc3m/asibot-configuration-files/blob/e02bfc67c363cf0353ad78921904ed50f59b1ac5/share/contexts/launchCanBus/manipulator-lacquey.ini#L1-L22

**Comment by PeterBowman** [comment]
Found by @smcdiaz and @jgvictores: [qt-1917.zip](https://github.com/roboticslab-uc3m/asibot-configuration-files/files/4041539/qt-1917.zip).

The (motor) torque constant, a.k.a. torque sensitivity (Kt), is 0.0862 Nm/A.
